### ISSUE TITLE
versionable computer-specific properties

### ISSUE THREAD

**Issue by mockitoguy** [unsaved/gradle-javaPropFile-plugin#1]
Hey.

I wonder if you could consider a feature to solve my use case: I would like to version my personal properties, e.g. commit them to the VCS so that they can act as reference for others and they don't disappear if I rid my workspace completely. In order to implement that in past, we used to have an extra folder with properties named like <computer name>.properties. The build was picking up the file depending on the environment, which was good enough approximation of 'personal' properties.

Cool plugin :) Thanks for sharing!

**Comment by unsaved** [comment]
I don't know what else you would want the plugin to do for this use case.  You can use the plugin as-is and add to your build.gradle something like

File personalProps = file('personals/' + System.properties['user.name'] + '.properties')
if (personalProps.isFile()) propFileLoader.load(personalProps)

**Comment by mockitoguy** [comment]
Any kind of api hinting at this solution would be cool because it would document the pattern. If you're not sure - leave it out. I was just throwing and idea :)

**Comment by unsaved** [comment]
FYI, per recommendation of the Gradle team, I'll be enhancing JavaPropFile to
allow setting of extension object properties.  They want to discourage addition
of properties directly in the Project object, to avoid conflicts within the
project singleton.  Unless I run into unanticipated difficulties, I hope to have
this done and published to Maven Central late on today.

On 11/20/2011 10:04 AM, Szczepan Faber wrote:

> Any kind of api hinting at this solution would be cool because it would document the pattern. If you're not sure - leave it out. I was just throwing and idea :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/unsaved/gradle-javaPropFile-plugin/issues/1#issuecomment-2804242

## 

http://admc.com/     Main:304-724-1433     Cell:540-877-0646

**Comment by unsaved** [comment]
Szczepan:

Wanted to say thanks for your support.  If nobody were using my plugins, it would hardly be worth the trouble to publish and document them, as I can use them myself without such efforts.  So, it's good to know that somebody else is using them.

**Comment by mockitoguy** [comment]
that sounds excellent!

On Sun, Nov 20, 2011 at 4:28 PM, Blaine Simpson <
reply@reply.github.com

> wrote:
> 
> Szczepan:
> 
> Wanted to say thanks for your support.  If nobody were using my plugins,
> it would hardly be worth the trouble to publish and document them, as I can
> use them myself without such efforts.  So, it's good to know that somebody
> else is using them.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/unsaved/gradle-javaPropFile-plugin/issues/1#issuecomment-2804332

## 

Szczepan Faber
Principal engineer@gradleware
Lead@mockito

**Comment by unsaved** [comment]
Version 0.3.0 available here, and within a few hours on Maven Central.

Sorry late.  Was busy getting a public build out for another project much larger and more complex than this one.  But in the past 2 days I added several more features to JavaPropFiles.

Besides extension object support, made system property behavior safer by always using namespace prefix for that, support arrays and arbitrary Collection types, allow escaping of all special JavaPropFile interpretations, allow user to toggle between '.' as character in property name vs. '.'-as-dereference-operator like in Groovy.  Over 50 unit tests.
