### ISSUE TITLE
Why not just use Gradle's integration with Ant?

### ISSUE THREAD

**Issue by sgoings** [unsaved/gradle-javaPropFile-plugin#4]
http://gradle.org/docs/current/userguide/ant.html

Specifically:

Load with:
`ant.property(file: 'messages.properties')`

Read by:
`ant.myvariable`
or
`ant.properties['my.longer.variable.with.dots']`

**Comment by unsaved** [comment]
That's great when the user will be satisfied with referencing variables in the "ant" scope, and when none of the several other JavaPropFiles features are needed, such as nesting, validation, explicit target-object-scoping, support for value types other than Strings, or expanding a file or String with specified properties.

For my own projects and those of most (or all) users of JavaPropFile, we need or want to populate variables to other scopes, like with project.description, or project.ext.customProjectProp, or compileJava.options.bootClasspath, or customClass.aFileObject.

So, agreed-- if you are satisfied with populating the ant scope and don't want any of the JavaPropFile features listed in the features page, then skip this product.
